<?php
// One place_holder template, so grab only the first place_holder elements
$ph1_blocks = isset($this->blocks[1]) ? $this->blocks[1] : array();
$ph2_blocks = isset($this->blocks[2]) ? $this->blocks[2] : array();
$ph3_blocks = isset($this->blocks[3]) ? $this->blocks[3] : array();
$ph4_blocks = isset($this->blocks[4]) ? $this->blocks[4] : array();
$controller = 'index';
?>
<div id="template" class="<?php echo $controller; ?>">
    <div class="zone1 zone-block full-large">
        <?php
        $options = array(
            'zoneId' => 1,
            'rows' => $ph1_blocks,
            'controller' => $controller,
            'isActive' => true
        );
        ?>
        <?php echo $this->zonesTemplate($options);?>
    </div>
    <div class="zone2 zone-block two-thirds">
        <?php
        $options = array(
            'zoneId' => 2,
            'rows' => $ph2_blocks,
            'controller' => $controller,
            'isActive' => true
        );
        ?>
        <?php echo $this->zonesTemplate($options); ?>
    </div>
    <div class="zone3 zone-block one-third">
        <?php
        $options = array(
            'zoneId' => 3,
            'rows' => $ph3_blocks,
            'controller' => $controller,
            'isActive' => true
        );
        ?>
        <?php echo $this->zonesTemplate($options); ?>
    </div>
    <div class="zone4 zone-block full-large">
        <!-- Placeholder 4 = special banners -->
        <?php
        $options = array(
            'zoneId' => 4,
            'rows' => $ph4_blocks,
            'controller' => $controller,
            'isActive' => true
        );
        ?>
        <?php echo $this->zonesTemplate($options); ?>
    </div>
</div>