<?php $x = 1; ?>
<?php
// Liste des styles à composer
$fontfamily='font-family:Arial,Helvetica,sans-serif;line-height:normal;';
$fontsize='font-size:16px;';
$colortext='color:#404040;';
$colorlink='color:#888888;';
$underline='text-decoration:underline;';
$nounderline='text-decoration:none;';
$colorTitre='color:#1E59CA;';
$formatageTitre=$fontfamily.$colorTitre.'font-size:23px;font-weight:bold;text-align:center;';
$formatageSlogan=$fontfamily.$colorTitre.'font-size:28px;font-weight:bold;text-align:center;';
$attributsImage=array('border'=>'0','style'=>'display:block;');
$spacer='font-size:1px;line-height:1px;-webkit-text-size-adjust:none;';

foreach ($this->articles as $article):
    if (!empty($article['NA_ImageSrc'])):

        $config = Zend_Registry::get('config')->toArray();
        $thumbMaxHeight = $config['newsletter']['image']['thumb']['maxHeight'];
        $thumbMaxWidth = $config['newsletter']['image']['thumb']['maxWidth'];
        $imgPath = Zend_Registry::get('absolute_web_root') . $this->currentSite . "/data/images/newsletter/"
            .$this->newsletterID.'/'.$article['NA_ID'].'/'
            . $thumbMaxWidth . 'x' . $thumbMaxHeight . '_' . $article['NA_ImageSrc'];
    endif;
    $tmpSrc = Zend_Registry::get('absolute_web_root') . $this->currentSite . '/data/images/';
    $borderB = ($x < count($this->articles)) ? $borderB : ' padding-bottom:18px;';
    $articleLink = '';
    if ($article['NA_TextLink'] == 1)
        $articleLink = Zend_Registry::get('absolute_web_root') . $this->details_page . "/" . $this->dateStringUrl . "/" . $this->parutionValUrl . "/" . $article['NA_ValUrl'] . '-uid-' . $this->memberId;
    elseif ($article['NA_TextLink'] == 2)
        $articleLink = $article['NA_URL'];
    ?>
    <table border="0" cellpadding="0" cellspacing="0" width="295">
            <?php if (!empty($article['NA_ImageSrc'])): ?>
            <tr>
                <td valign="top" style="text-align:center;">
                    <?php $show = true; ?>
                    <?php $img = $this->image($imgPath, array('style' => 'display:block;margin-left:auto;margin-right:auto;', 'alt' => $article['NA_ImageAlt'])); ?>
                    <?php
                    if (!empty($articleLink)):
                        $link = $this->link($articleLink, $img);
                        echo $link;
                    else:
                        echo $img;
                    endif;
                    ?>
                </td>
            </tr>
            <tr><td style="<?php echo $spacer; ?>" height="27"></td></tr>
            <?php endif; ?>
            <tr>
                <td style="<?php echo $fontfamily.$colorTitre; ?>font-size:18px;">
                    <?php echo($article['NA_Title']); ?>
                </td>
            </tr>
            <tr><td style="<?php echo $spacer; ?>" height="27"></td></tr>
            <tr>
                <td>
                    <?php
                    if ($article['NA_Resume']){
                        $search = array('src="/data/images/', '##uid##');
                        $replace = array('src="' . $tmpSrc, $this->memberId);
                        echo str_replace($search, $replace, $article['NA_Resume']);
                    }
                    ?>
                </td>
            </tr>
            <tr><td style="<?php echo $spacer; ?>" height="11"></td></tr>
            <tr>
                <td style="text-align:center;">
                    <?php
                    if (!empty($articleLink)):
                        $imgLink = $this->image($this->locateFile('btn-ensavoirplus.gif', $this->repertoireLangueImages,'front'), array('direct' => true, 'alt' => $this->getClientText('see_details_news_text')));
                        $link = $this->link($articleLink, $imgLink, array('style' => 'color:#fff;text-decoration:none;', 'title' => $this->getClientText('see_details_news_text')));
                    ?>
                    <?php echo $link; ?>
                    <?php endif; ?>
                </td>
            </tr>
            <tr><td style="<?php echo $spacer; ?>" height="44"></td></tr>
    </table>
    <?php $x++; ?>
<?php endforeach; ?>