<?php
$action  = $this->action;
$data    = $this->data;
?>
<section class="imageslibrary module delete">
<?php if ($data):?>
    <h3><?php echo $data['ILI_Label1'] ?></h3>
    <p><?php echo $this->getCibleText('confirm_delete_record'); ?></p>
    <form action="<?php echo $this->url(array('action'=>$action)); ?>" method="post">
        <div>
            <input type="hidden" name="blockID" value="<?php echo $this->cleaction ?>" />
            <input type="submit" name="delete" value="<?php echo $this->getCibleText('button_yes') ?>" />
            <input type="submit" name="cancel" value="<?php echo $this->getCibleText('button_no') ?>" />
        </div>
    </form>
<?php else:?>
    <p><?php echo $this->getCibleText('header_delete_'.$this->cleaction.'_text') ?></p>
      <a href="<?php echo ($this->return); ?>">Retour</a>
<?php endif; ?>
</section>