
<?php
$imagesData = !empty($this->mylist) ? $this->mylist : $this->imagesData;
$random = rand(1, 100000000);
$nbToDisplay = 1;
if (isset($_SESSION['imgIndex']))
    $imgIndex = $_SESSION['imgIndex'];
else
    $imgIndex = $_SESSION['imgIndex'] = 1;

$countImages = count($imagesData->getCurrentItems());


if ($countImages > 0):
    ?>
    <section data-magnificcontainer="<?php echo $random ?>" class="imageslibrary slidelist module block <?php echo ($this->effect == "scrollVert") ? 'verticalslider' : 'horizontalslider' ?>">
        <?php echo $this->showBlockTitle('h2', array('class' => 'imageslibrary-title'));?>
        <div class="imageslibrary-container">
            <div class="imageslibrary-slidelist" id="slideshow-<?php echo $random; ?>">
                <div class="imageslibrary-slidelist-group">
                    <?php
                    foreach ($imagesData as $index => $image):
                        if (!isset($image['IL_Video']))
                            $image['IL_Video'] = "";

                        $imageS = $this->moduleImage('imageslibrary', $image['IL_ID'], $image['IL_Filename'], 'thumbList', array('getSource' => 'true', 'prettyPhoto' => array()));

                          $videoLink = 0;  // 0 = no video / no link, 1 = video , 2 = link
                        if ($image['IL_Video'] != "") {
                            $imageSFull = $image['IL_Video'];
                            $videoLink = 1;
                        } elseif ($image['ILI_Link'] != "") {
                            $imageSFull = $image['ILI_Link'];
                            $videoLink = 2;
                        } else {
                            $imageSFull = $this->moduleImage('imageslibrary', $image['IL_ID'], $image['IL_Filename'], 'original', array('getSource' => 'true', 'prettyPhoto' => array()));
                        }
                        if ($index % $nbToDisplay == 0 && $index != 0):
                            ?>
                        </div>
                        <div class="imageslibrary-slidelist-group">
                            <?php
                        endif;
                        ?>
                        <?php if ($this->prettyPhoto) { ?>
                            <a data-magnific="<?php echo $random ?>" title='<?php echo Cible_FunctionsGeneral::truncateString(strip_tags($image['ILI_Description']), 500) ?>' class='imageslibrary-slide <?php
                            if ($videoLink != 2) {
                                echo 'prettyPhoto';
                            }
                            ?>'  <?php if ($videoLink == 2) { ?> target="_blank" <?php } ?> href='<?php echo $imageSFull; ?>'>
                                <?php } else {
                                    ?>
                                <span class="imageslibrary-slide">
                                    <?php
                                }
                                ?>
                                <span class="imageslibrary-slide-container">
                                    <img class='imageslibrary-slide-image' src='<?php echo $imageS; ?>' alt='<?php echo strip_tags($image['ILI_Label1']) ?>' />                                
                                </span>
                        <?php if ($this->prettyPhoto) { ?>
                            </a>
                        <?php } 
                        
                        ?>
                             <?php if ($image['ILI_Label1'] != ""): ?>
                                    <div class='title' >
                                        <?php echo $image['ILI_Label1'] ?>
                                    </div>
                             <?php endif; ?>     
                            <?php
           
                       

                    endforeach;
                    ?>
                </div>
            </div>
            <?php if ($this->navi) : ?>
                <nav class='imageslibrary-nav'>
                    <div class="imageslibrary-prev" id="leftCycle-<?php echo $random; ?>">prev</div>
                    <div class="imageslibrary-next" id="rightCycle-<?php echo $random; ?>">next</div>
                </nav>
            <?php endif; ?>
        </div>
    </section>
<?php else: ?>
    <div class="imageslibrary-empty"><?php echo $this->getCibleText('gallery_no_gallery'); ?></div>
<?php endif; ?>

<?php $this->placeholder('footerScript')->captureStart(); ?>
<script type="text/javascript">
//<![CDATA[
    $(window).load(function() {
    
    $(window).resize(function(){
        var hauteur=0;
        $('#slideshow-<?php echo $random; ?> .title').css('height','auto');
        $('#slideshow-<?php echo $random; ?> .title').each(function(){
            if($(this).outerHeight()>hauteur){
                hauteur=$(this).outerHeight();
            }
        });
        $('#slideshow-<?php echo $random; ?> .title').css('height',hauteur+'px');
    })
    $(window).resize();
    var $slideshow = $('#slideshow-<?php echo $random; ?>');
            $slideshow.cycle({
            fx: "<?php echo $this->effect ?>",
<?php if ($this->navi) : ?>
            prev : '#leftCycle-<?php echo $random; ?>',
            next : '#rightCycle-<?php echo $random; ?>',
<?php endif; ?>
            slides : "> div",
<?php if ($this->fx != "scrollVert"): ?>
                swipe: true,
<?php endif; ?>
            speed : <?php echo ($this->autoPlay) ? $this->transition : 0 ?>,
            timeout : <?php echo $this->delais * 1000 ?>,
            //manualTrump:false,
            log: false

            });
    }).resize();
//]]>
</script>
<?php $this->placeholder('footerScript')->captureEnd(); ?>