<?php
$lang = $this->view->languageId;
$config = Zend_Registry::get('config');
$edith_logo = $this->link('#', $this->clientImage('logo.png',
    array('alt' => "", 'title' => "")));
$array_replace = array('<p>' => '', '<P>' => '', '</p>' => '', '</P>' => '',
    '%%%GET_DATE_YEAR%%%' => date('Y'),
    '%%%SITE_NAME%%%' => $config->site->title->$lang);
$copyrightText = $this->getClientText('footer_copyright', null, $array_replace);
?>

<section class="well6">
    <div class="container center767 wow fadeIn" data-wow-duration="2s" data-wow-delay="0.2s">
        <div class="row">
            <div class="col-md-4 col-sm-6 col-xs-6">
                <h2 class="navbar-brand">
                    <a href="./">marché</a>
                    <span class="brand-slogan">de l'Imprimerie </span>
                </h2>
            </div>

            <div class="col-md-2 col-sm-6 col-xs-6  wow fadeIn" >
                <h4 class="txt-clr1">&nbsp;</h4>
                <?php echo $this->menu('footer',
    array('parentIdAlt' => 'footer1ParentId', 'class' => 'site-footer-menu')) ?>
            </div>
            <div class="col-md-4 col-sm-6 col-xs-6 fb-plug-wr">
                <!-- Go to www.addthis.com/dashboard to customize your tools -->
                <div class="addthis_sharing_toolbox"></div>
            </div>
        </div>
    </div>
</section>
<script type="text/javascript" src="<?php echo $this->locateFile('tm-scripts.js'); ?>"></script>
<?php
if($config->searchbox->embeded)
    echo $this->partial('partials/jsSearchBox.phtml')
?>
<?php if(Zend_Registry::isRegistered('disabledFieldStatus') && !Zend_Registry::get('disabledFieldStatus')): ?>
    <script type="text/javascript" src="<?php echo $this->locateFile('manageChangedFields.js',
        null, 'back'); ?>"></script>
<?php endif; ?>
<?php echo $this->placeholder('footerScript'); ?>
<!--<script type="text/javascript" src="<?php // echo $this->locateFile('jsAddToCart.js'); ?>"></script>-->
<?php // echo $this->partial('partials/jsCatalog.phtml', 'catalog'); ?>
<script type="text/javascript">
    var arrayUnique = function (a) {
        return a.reduce(function (p, c) {
            if (p.indexOf(c) < 0)
                p.push(c);
            return p;
        }, []);
    };
</script>