<?php
$config = Zend_Registry::get("config");
$lang = $this->view->languageId;
$replace = array('<p>' => '', '<P>' => '', '</p>' => '', '</P>' => ''
    , '%%%SITE_NAME%%%' => $config->site->title->$lang);
$imgAlt = $this->getClientText('home_page_link_title', null, $replace);
$imageFirstALT = "";
if(Zend_Registry::isRegistered('altImageFirst')){
    $imageFirstALT = Zend_Registry::get('altImageFirst');
}
if($imageFirstALT == "")
{
    if(Zend_Registry::isRegistered('pageTitle')){
        $imageFirstALT = Zend_Registry::get('pageTitle');
    }else if($imgAlt != ""){
        $imageFirstALT = $imgAlt;
    }else{
        $imageFirstALT = $config->site->title->$lang;
    }
}
?>

<div id="stuck_container" class="stuck_container">
    <nav class="navbar navbar-default navbar-static-top clearfix">
        <div class="container">
            <div class="navbar-header">
                <h1 class="navbar-brand">
                    <a href="./">marché</a>
                    <span class="brand-slogan">de l'Imprimerie</span>
                </h1>
            </div>
            <div class="navbar-right">
                <?php
        echo $this->menu(
            'principal',
            array(
            'class' => 'nav navbar-nav',
            'id' => 'menu-principal',
            'maxLevel' => 3,
            'dropdownMenuClass' => 'dropdown-menu',
            'dropdownClass' => 'dropdown',
            'parentAltId' => 'parentIdTop-',
             'attribs' => array('data-type'=>"navbar")
                )
        );
        echo $this->languageSwitcher(array('use_suffix' => true));
        ?>
        <?php
        echo $this->menu(
            'header',
            array(
            'class' => 'site-menu-icons nav navbar-nav',
            'id' => 'menu-secondaire',
            'isDropdownMenu' => true,
            'dropdownMenuClass' => 'dropdown-menu',
            'dropdownClass' => 'dropdown',
            'parentAltId' => 'parentIdTop-')
        );
        ?>
<!--                <ul class="navbar-nav sf-menu" data-type="navbar">
                    <li class="active">
                        <a href="./">Accueil</a>
                    </li>
                    <li>
                        <a href="/contact-us">Nous joindre</a>
                    </li>
                </ul>-->
            </div>
        </div>
    </nav>
</div>
