<?php
// One place_holder template, so grab only the first place_holder elements
$emptyPlaceholders = $this->zonesBlocks(array('nbZones' => $this->nbZones));

$tree = $this->subMenu(array('id' => 'submenu', 'class' => 'open', 'buildOnCatalog' => true));
$menu = $this->menu($tree, array(
    'id' => 'submenu',
    'startLevel' => 2,
    'maxLevel' => 4,
    'parentIdAlt' => 'subMenu-',
    'parentId' => $tree['MID_ParentId'],
    'class' => 'nav nav-pills nav-stacked')
    );
$withLeftMenu = 'col-md-12 site-main-without-menu';

$breadCrumb = $this->breadcrumbmenu(array('menuTitle' => 'principal',
    'showHomeClass' => 'breadcrumb-home')
);
?>
<?php if (isset($tree[0])): ?>
    <?php $withLeftMenu = 'col-md-9 site-main-with-menu'; ?>
<?php endif; ?>

<section class="bg-alt">
    <div class="container center991">
        <?php echo $this->placeholder('zone1') ?>
    </div>
</section>
