<?php echo $this->doctype();?>
<!--[if IE 7]>
<html class="ie ie7 desktop" lang="<?php echo(Zend_Registry::get("languageSuffix")); ?>">
<![endif]-->
<!--[if IE 8]>
<html class="ie ie8 desktop" lang="<?php echo(Zend_Registry::get("languageSuffix")); ?>">
<![endif]-->
<!--[if IE 9]>
<html class="ie ie9 desktop" lang="<?php echo(Zend_Registry::get("languageSuffix")); ?>">
<![endif]-->
<html class="not-ie desktop" lang="<?php echo(Zend_Registry::get("languageSuffix")); ?>">
    <!--<![endif]-->
    <head>
        <title><?php echo $this->headTitle(); ?></title>
        <!-- META (START) -->
        <?php echo $this->headMeta() ?>
        <?php echo $this->placeholder('metaOther'); ?>
        <!--[if IE]>
        <link rel="shortcut icon" href="<?php echo $this->locateFile('favicon.ico') ?>" />
        <![endif]-->
        <link rel="icon" type="image/png" href="<?php echo $this->locateFile('favicon.png') ?>" />
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>

        <!-- Tag to force the AddThis thumbnail image
        <link rel='image_src' href='<?php echo Zend_Registry::get('addThis') ?>' /> -->
        <?php echo $this->partial('partials/' . $this->analytic); ?>
        <?php
        if (Zend_Registry::isRegistered('bgStyle'))
            $bgStyle = Zend_Registry::get('bgStyle');
        else
            $bgStyle = '';
        ?>
        <!--[if !IE 7]>
            <style type="text/css">
                #wrap {display:table;height:100%}
            </style>
        <![endif]-->
        <style>
            .site-background {
                background-image:url(<?php echo $this->imgBackHeader; ?>);
                background-position: 50% 0;
            }
        </style>
        <?php echo $this->jQuery(); ?>
        <?php if (ISDEV): ?>
        <script src="https://code.jquery.com/jquery-migrate-1.2.1.js"></script>
        <?php endif; ?>
        <?php $this->headScript()->appendFile($this->locateFile('modernizr.js')); ?>
        <?php echo $this->headScript() ?>
    </head>

    <body class="front-end template <?php echo $this->templateName; ?>" <?php echo $bgStyle; ?> >
        <div class="page">
            <!-- Start : HEADER -->
            <header class="site-header" role="banner">
                <?php echo $this->partial('partials/' . $this->header, array('view' => $this)) ?>
            </header>
            <!-- End : HEADER -->
            <!-- Start : MAIN -->
            <main>
                <?php echo $this->layout()->content; ?>
            </main>
            <!-- End : MAIN -->
            <!-- Start : FOOTER -->
            <footer class="bg-secondary" role="contentinfo">
                <?php echo $this->partial('partials/' . $this->footer, array('view' => $this)) ?>
            </footer>
            <!-- END : Footer -->

        </div>

        <?php echo $this->partial('partials/jsPrettyPhoto.phtml') ?>
        <!--[if lt IE 9]>
            <script type="text/javascript" src="<?php echo $this->locateFile('respond.min.js'); ?>"></script>
            <script src="<?php echo $this->locateFile('html5shiv.min.js'); ?>"></script>
            <![endif]-->
    </body>
</html>
